{% set name = "sinabs-exodus" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sinabs-exodus-{{ version }}.tar.gz
  sha256: 95b874fd1e2ae9d02bbd4300812d9479cae94b4dfafb02c9fdbdfac9b16b9e53
  patches:
    - fix-hardcoded-compiler.patch

build:
  number: 3
  skip: true  # [win or osx or cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  missing_dso_whitelist:
    # pytorch builds put the libs in the wrong place, but hard to unbundle, see
    # https://github.com/conda-forge/staged-recipes/pull/17082#issuecomment-1189149813
    - '*/libc10{{ SHLIB_EXT }}'
    - '*/libc10_cuda{{ SHLIB_EXT }}'
    - '*/libtorch{{ SHLIB_EXT }}'
    - '*/libtorch_cpu{{ SHLIB_EXT }}'
    - '*/libtorch_cuda{{ SHLIB_EXT }}'
    - '*/libtorch_python{{ SHLIB_EXT }}'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    # see https://github.com/conda-forge/linux-sysroot-feedstock/issues/52
    - libxcrypt  # [linux and py<39]
  host:
    - versioneer
    - python
    - pytorch
    - pip
    - setuptools
    - cuda-cudart-dev  # [(cuda_compiler_version or "").startswith("12")]
  run:
    - python
    - pytorch
    - sinabs
    - __cuda

test:
  imports:
    - sinabs.exodus
    - sinabs.exodus.layers
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  summary: Efficient training and inference on GPU for sinabs spiking neural network simulator.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/synsense/sinabs-exodus

extra:
  recipe-maintainers:
    - Tobias-Fischer
