context:
  name: sinabs-exodus
  version: 2.0.0
  build_number: 6

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sinabs-exodus-${{ version }}.tar.gz
  sha256: 4d4e61da73aa7031a0b6be030afb9035a120b15dacfa9e034ff18006cefd37a5
  patches:
    - fix-hardcoded-compiler.patch

build:
  number: ${{ build_number }}
  skip:
    - win
    - osx
    - cuda_compiler_version == "None"
  string: cuda${{ cuda_compiler_version | replace(".", "") }}py${{ python | replace(".", "") }}h${{ hash }}_${{ build_number }}
  dynamic_linking:
    # pytorch builds put the libraries in the wrong place.
    missing_dso_allowlist:
      - "*/libc10.so"
      - "*/libc10_cuda.so"
      - "*/libtorch.so"
      - "*/libtorch_cpu.so"
      - "*/libtorch_cuda.so"
      - "*/libtorch_python.so"

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-version ${{ cuda_compiler_version }}.*
  host:
    - versioneer
    - python
    - pytorch
    - pip
    - setuptools
    - cuda-cudart-dev
    - cuda-version ${{ cuda_compiler_version }}.*
  run:
    - python
    - pytorch
    - sinabs >=3
    - numpy

tests:
  - python:
      imports:
        - sinabs.exodus
        - sinabs.exodus.layers

about:
  summary: Efficient training and inference on GPU for sinabs spiking neural network simulator.
  license: AGPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/synsense/sinabs-exodus

extra:
  recipe-maintainers:
    - Tobias-Fischer

